// <auto-generated />
namespace Movie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addcomment_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcomment_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170106236_add comment_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
